Repository dhghf/matrix-appservice-minecraft, pull requests merged in 2020-06, with the labels that each got.

#12 Patched Issue #4
  README.md
  package.json
  src/matrix/MatrixManager.ts
  src/minecraft/PlayerManager.ts
  src/minecraft/internal/Player.ts
Labels: bug

#13 Patched Issue #11
  .gitignore
  README.md
  package.json
  src/Marco.ts
  src/common/BridgeManager.ts
  src/common/Config.ts
  src/db/BridgeTable.ts
  src/db/DBController.ts
  src/matrix/MatrixManager.ts
  src/matrix/internal/RegManager.ts
  src/webserver/WebServer.ts
  src/webserver/internal/errors.ts
  src/webserver/internal/routes/chat/getChat.ts
  src/webserver/internal/routes/chat/postChat.ts
  yarn.lock
Labels: enhancement

#18 Patched #8
  README.md
  docs/Classes.md
  docs/Endpoints.md
  docs/README.md
  docs/res/made-for-matrix.png
  package.json
  src/Config.ts
  src/Main.ts
  src/Marco.ts
  src/app.ts
  src/bridging/Bridge.ts
  src/bridging/BridgeManager.ts
  src/bridging/errors.ts
  src/bridging/index.ts
  src/common/errors.ts
  src/db/DBController.ts
  src/db/index.ts
  src/db/tables/BridgeTable.ts
  src/matrix/MatrixInterface.ts
  src/matrix/index.ts
  src/matrix/internal/CmdManager.ts
  src/matrix/internal/MsgProcessor.ts
  src/matrix/internal/RegManager.ts
  src/minecraft/index.ts
  src/minecraft/internal/types.ts
  src/webserver/WebInterface.ts
  src/webserver/index.ts
  src/webserver/internal/errors.ts
  src/webserver/internal/routes/chat/getChat.ts
  src/webserver/internal/routes/chat/postChat.ts
Labels: documentation, enhancement

#20 Patched Issue #19
  package.json
  src/Config.ts
  src/Main.ts
  src/matrix/MatrixInterface.ts
  src/webserver/WebInterface.ts
  yarn.lock
Labels: enhancement

#22 vibeCheck: Report errors similarly to other endpoints
  src/webserver/WebInterface.ts
Labels: bug, enhancement

#23 Patched Issue #7
  src/matrix/MatrixInterface.ts
  src/matrix/internal/CmdManager.ts
  src/webserver/WebInterface.ts
  src/webserver/internal/routes/chat/getChat.ts
  src/webserver/internal/routes/chat/postChat.ts
Labels: enhancement
